/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cineseek/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 자연어로 영화 검색 */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 감독·배우 자동완성 */
        get: operations["people"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 인물 이름 조회 (필터 칩 라벨 복원용) */
        get: operations["person"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/people/{id}/filmography": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 배우 필모그래피 — 저장된 출연작을 최신순·평점순으로 */
        get: operations["filmography"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 장르·인물 조건으로 영화 탐색 */
        get: operations["explore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/movies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 영화 상세 */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/movies/{id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 줄거리가 비슷한 영화 */
        get: operations["similar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 장르 목록 */
        get: operations["genres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenreResponse: {
            /**
             * Format: int64
             * @description TMDB 장르 id
             * @example 28
             */
            id?: number;
            name?: string;
            nameKo?: string | null;
        };
        PageResponse: {
            /** Format: int32 */
            limit?: number;
            /** Format: int32 */
            offset?: number;
            hasNext?: boolean;
            /**
             * Format: int64
             * @description 미제공 — 하이브리드 검색 전체 count 비용
             */
            total?: number | null;
        };
        SearchItemResponse: {
            /** Format: int64 */
            movieId?: number;
            title?: string;
            originalTitle?: string | null;
            /** Format: int32 */
            releaseYear?: number | null;
            /** Format: double */
            rating?: number | null;
            /** Format: int32 */
            voteCount?: number | null;
            posterPath?: string | null;
            genres?: components["schemas"]["GenreResponse"][];
            /**
             * Format: double
             * @description 검색은 RRF 점수, 유사 영화는 코사인 유사도
             * @example 0.032
             */
            score?: number;
        };
        SearchResponse: {
            /** @description 검색 결과 (점수 내림차순) */
            items?: components["schemas"]["SearchItemResponse"][];
            page?: components["schemas"]["PageResponse"];
        };
        PeopleResponse: {
            items?: components["schemas"]["PersonItemResponse"][];
        };
        PersonItemResponse: {
            /** Format: int64 */
            personId?: number;
            name?: string;
            role?: string;
            knownFor?: string[];
        };
        MovieCardResponse: {
            /** Format: int64 */
            movieId?: number;
            title?: string;
            originalTitle?: string | null;
            /** Format: int32 */
            releaseYear?: number | null;
            /**
             * Format: double
             * @description TMDB 평점 (0~10)
             * @example 8.7
             */
            rating?: number | null;
            /** Format: int32 */
            voteCount?: number | null;
            posterPath?: string | null;
            genres?: components["schemas"]["GenreResponse"][];
        };
        MovieListResponse: {
            items?: components["schemas"]["MovieCardResponse"][];
            page?: components["schemas"]["PageResponse"];
        };
        CastMemberResponse: {
            /** Format: int64 */
            personId?: number;
            name?: string;
            character?: string | null;
        };
        MovieDetailResponse: {
            /** Format: int64 */
            movieId?: number;
            title?: string;
            originalTitle?: string | null;
            /** Format: int32 */
            releaseYear?: number | null;
            /** Format: int32 */
            runtime?: number | null;
            /** Format: double */
            rating?: number | null;
            /** Format: int32 */
            voteCount?: number | null;
            posterPath?: string | null;
            overview?: string | null;
            genres?: components["schemas"]["GenreResponse"][];
            directors?: components["schemas"]["PersonResponse"][];
            cast?: components["schemas"]["CastMemberResponse"][];
        };
        PersonResponse: {
            /** Format: int64 */
            personId?: number;
            name?: string;
        };
        GenresResponse: {
            items?: components["schemas"]["GenreResponse"][];
        };
        FilmographyPersonResponse: {
            /**
             * Format: int64
             * @description TMDB person id
             * @example 3895
             */
            personId?: number;
            /**
             * @description 이름
             * @example 크리스찬 베일
             */
            name?: string;
            /**
             * @description TMDB 프로필 이미지 경로
             * @example /fuTEtOeIwXiqtVpIoL0GyyWcnxh.jpg
             */
            profilePath?: string | null;
            /**
             * @description 필모그래피 수집 상태 (NONE | COLLECTING | COMPLETE)
             * @example COMPLETE
             * @enum {string}
             */
            filmoState?: "NONE" | "COLLECTING" | "COMPLETE";
            /**
             * Format: date-time
             * @description 필모그래피 마지막 갱신 확인 시각
             * @example 2026-10-01T00:00:00Z
             */
            filmoCheckedAt?: string | null;
            /**
             * Format: int64
             * @description 총 출연 작품 수 (movie_cast 행 수)
             * @example 47
             */
            totalWorks?: number;
        };
        FilmographyItemResponse: {
            /**
             * Format: int64
             * @description 영화 id
             * @example 155
             */
            movieId?: number;
            /**
             * @description 제목
             * @example 다크 나이트
             */
            title?: string;
            /**
             * @description 원제
             * @example The Dark Knight
             */
            originalTitle?: string | null;
            /**
             * Format: int32
             * @description 개봉 연도
             * @example 2008
             */
            releaseYear?: number | null;
            /**
             * Format: double
             * @description TMDB 평점 (0~10)
             * @example 8.5
             */
            rating?: number | null;
            /**
             * Format: int32
             * @description TMDB 투표 수
             * @example 30000
             */
            voteCount?: number | null;
            /**
             * @description 포스터 이미지 경로
             * @example /qJ2tW6WMUDux911r6m7haRef0WH.jpg
             */
            posterPath?: string | null;
            /** @description 장르 목록 */
            genres?: components["schemas"]["GenreResponse"][];
            /**
             * @description 해당 배우의 배역명
             * @example 브루스 웨인
             */
            character?: string | null;
        };
        FilmographyResponse: {
            person?: components["schemas"]["FilmographyPersonResponse"];
            items?: components["schemas"]["FilmographyItemResponse"][];
            page?: components["schemas"]["PageResponse"];
            /**
             * @description 필모그래피 백그라운드 갱신이 대기/실행 중인지 — true면 잠시 후 다시 조회해 갱신된 목록을 받는다
             * @example false
             */
            collecting?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search: {
        parameters: {
            query: {
                /**
                 * @description 검색어 (줄거리 묘사)
                 * @example 감옥에서 탈출하는 이야기
                 */
                q: string;
                /**
                 * @description 장르 id (반복 파라미터, OR)
                 * @example [
                 *       80
                 *     ]
                 */
                genreId?: number[];
                /**
                 * @description 개봉 연도 하한
                 * @example 2000
                 */
                yearMin?: number;
                /**
                 * @description 개봉 연도 상한
                 * @example 2020
                 */
                yearMax?: number;
                /**
                 * @description 평점 하한 (0~10)
                 * @example 7.5
                 */
                ratingMin?: number;
                /**
                 * @description 러닝타임 하한 (분)
                 * @example 90
                 */
                runtimeMin?: number;
                /**
                 * @description 러닝타임 상한 (분)
                 * @example 150
                 */
                runtimeMax?: number;
                /**
                 * @description 투표 수 하한 — 숨은 명작 탐색용
                 * @example 50
                 */
                voteCountMin?: number;
                /**
                 * @description 투표 수 상한 — 숨은 명작 탐색용
                 * @example 500
                 */
                voteCountMax?: number;
                /**
                 * @description 감독 person id
                 * @example 525
                 */
                directorId?: number;
                /**
                 * @description 배우 person id
                 * @example 3895
                 */
                castId?: number;
                /**
                 * @description 결과 수 (1~50)
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description 건너뛸 결과 수
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    people: {
        parameters: {
            query: {
                /**
                 * @description 이름 접두어
                 * @example 봉
                 */
                q: string;
                /**
                 * @description 역할 (director | cast)
                 * @example director
                 */
                role?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PeopleResponse"];
                };
            };
        };
    };
    person: {
        parameters: {
            query?: {
                /**
                 * @description 역할 (director | cast)
                 * @example director
                 */
                role?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonItemResponse"];
                };
            };
        };
    };
    filmography: {
        parameters: {
            query?: {
                /**
                 * @description 정렬 (release | rating) — 기본 최신 개봉순
                 * @example release
                 */
                sort?: string;
                /**
                 * @description 페이지 (0부터)
                 * @example 0
                 */
                page?: number;
                /**
                 * @description 페이지 크기 (1~50)
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description 제외할 영화 id — 영화 상세의 '주요 배우 다른 작품'에서 현재 영화 제외
                 * @example 155
                 */
                excludeMovieId?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FilmographyResponse"];
                };
            };
        };
    };
    explore: {
        parameters: {
            query?: {
                /**
                 * @description 장르 id
                 * @example 28
                 */
                genreId?: number;
                /**
                 * @description 정렬 (rating | release | vote_count)
                 * @example rating
                 */
                sort?: string;
                /**
                 * @description 페이지 (0부터)
                 * @example 0
                 */
                page?: number;
                /**
                 * @description 페이지 크기 (1~50)
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description 감독 person id
                 * @example 525
                 */
                directorId?: number;
                /**
                 * @description 배우 person id
                 * @example 3895
                 */
                castId?: number;
                /**
                 * @description 평점 하한 (0~10)
                 * @example 7.5
                 */
                ratingMin?: number;
                /**
                 * @description 최소 투표 수 — 명시하면 평점순 암시 하한(1000) 대신 적용
                 * @example 50
                 */
                voteCountMin?: number;
                /**
                 * @description 최대 투표 수 (숨은 명작 탐색용)
                 * @example 500
                 */
                voteCountMax?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieListResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieDetailResponse"];
                };
            };
        };
    };
    similar: {
        parameters: {
            query?: {
                /**
                 * @description 결과 수 (1~20)
                 * @example 8
                 */
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    genres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenresResponse"];
                };
            };
        };
    };
}
