/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cineseek/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 자연어로 영화 검색 */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 감독·배우 자동완성 */
        get: operations["people"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 인물 이름 조회 (필터 칩 라벨 복원용) */
        get: operations["person"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 장르·인물 조건으로 영화 탐색 */
        get: operations["explore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/movies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 영화 상세 */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/movies/{id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 줄거리가 비슷한 영화 */
        get: operations["similar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cineseek/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 장르 목록 */
        get: operations["genres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenreResponse: {
            /**
             * Format: int64
             * @description TMDB 장르 id
             * @example 28
             */
            id?: number;
            name?: string;
            nameKo?: string | null;
        };
        PageResponse: {
            /** Format: int32 */
            limit?: number;
            /** Format: int32 */
            offset?: number;
            hasNext?: boolean;
            /**
             * Format: int64
             * @description 미제공 — 하이브리드 검색 전체 count 비용
             */
            total?: number | null;
        };
        SearchItemResponse: {
            /** Format: int64 */
            movieId?: number;
            title?: string;
            originalTitle?: string | null;
            /** Format: int32 */
            releaseYear?: number | null;
            /** Format: double */
            rating?: number | null;
            /** Format: int32 */
            voteCount?: number | null;
            posterPath?: string | null;
            genres?: components["schemas"]["GenreResponse"][];
            /**
             * Format: double
             * @description 검색은 RRF 점수, 유사 영화는 코사인 유사도
             * @example 0.032
             */
            score?: number;
        };
        SearchResponse: {
            /** @description 검색 결과 (점수 내림차순) */
            items?: components["schemas"]["SearchItemResponse"][];
            page?: components["schemas"]["PageResponse"];
        };
        PeopleResponse: {
            items?: components["schemas"]["PersonItemResponse"][];
        };
        PersonItemResponse: {
            /** Format: int64 */
            personId?: number;
            name?: string;
            role?: string;
            knownFor?: string[];
        };
        MovieCardResponse: {
            /** Format: int64 */
            movieId?: number;
            title?: string;
            originalTitle?: string | null;
            /** Format: int32 */
            releaseYear?: number | null;
            /**
             * Format: double
             * @description TMDB 평점 (0~10)
             * @example 8.7
             */
            rating?: number | null;
            /** Format: int32 */
            voteCount?: number | null;
            posterPath?: string | null;
            genres?: components["schemas"]["GenreResponse"][];
        };
        MovieListResponse: {
            items?: components["schemas"]["MovieCardResponse"][];
            page?: components["schemas"]["PageResponse"];
        };
        CastMemberResponse: {
            /** Format: int64 */
            personId?: number;
            name?: string;
            character?: string | null;
        };
        MovieDetailResponse: {
            /** Format: int64 */
            movieId?: number;
            title?: string;
            originalTitle?: string | null;
            /** Format: int32 */
            releaseYear?: number | null;
            /** Format: int32 */
            runtime?: number | null;
            /** Format: double */
            rating?: number | null;
            /** Format: int32 */
            voteCount?: number | null;
            posterPath?: string | null;
            overview?: string | null;
            genres?: components["schemas"]["GenreResponse"][];
            directors?: components["schemas"]["PersonResponse"][];
            cast?: components["schemas"]["CastMemberResponse"][];
        };
        PersonResponse: {
            /** Format: int64 */
            personId?: number;
            name?: string;
        };
        GenresResponse: {
            items?: components["schemas"]["GenreResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search: {
        parameters: {
            query: {
                /**
                 * @description 검색어 (줄거리 묘사)
                 * @example 감옥에서 탈출하는 이야기
                 */
                q: string;
                /**
                 * @description 장르 id (반복 파라미터, OR)
                 * @example [
                 *       80
                 *     ]
                 */
                genreId?: number[];
                /**
                 * @description 개봉 연도 하한
                 * @example 2000
                 */
                yearMin?: number;
                /**
                 * @description 개봉 연도 상한
                 * @example 2020
                 */
                yearMax?: number;
                /**
                 * @description 평점 하한 (0~10)
                 * @example 7.5
                 */
                ratingMin?: number;
                /**
                 * @description 감독 person id
                 * @example 525
                 */
                directorId?: number;
                /**
                 * @description 배우 person id
                 * @example 3895
                 */
                castId?: number;
                /**
                 * @description 결과 수 (1~50)
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description 건너뛸 결과 수
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    people: {
        parameters: {
            query: {
                /**
                 * @description 이름 접두어
                 * @example 봉
                 */
                q: string;
                /**
                 * @description 역할 (director | cast)
                 * @example director
                 */
                role?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PeopleResponse"];
                };
            };
        };
    };
    person: {
        parameters: {
            query?: {
                /**
                 * @description 역할 (director | cast)
                 * @example director
                 */
                role?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonItemResponse"];
                };
            };
        };
    };
    explore: {
        parameters: {
            query?: {
                /**
                 * @description 장르 id
                 * @example 28
                 */
                genreId?: number;
                /**
                 * @description 정렬 (rating | release | vote_count)
                 * @example rating
                 */
                sort?: string;
                /**
                 * @description 페이지 (0부터)
                 * @example 0
                 */
                page?: number;
                /**
                 * @description 페이지 크기 (1~50)
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description 감독 person id
                 * @example 525
                 */
                directorId?: number;
                /**
                 * @description 배우 person id
                 * @example 3895
                 */
                castId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieListResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovieDetailResponse"];
                };
            };
        };
    };
    similar: {
        parameters: {
            query?: {
                /**
                 * @description 결과 수 (1~20)
                 * @example 8
                 */
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    genres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenresResponse"];
                };
            };
        };
    };
}
